name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  APP_DEBUG: true
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: lampsitedb
  DB_USERNAME: root
  DB_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v2
      # Setup environment
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: variables_order=GPCS, request_order=GP
      - uses: "ramsey/composer-install@v1"
      - name: Setup .env
        run: |
          echo APP_DEBUG=${{ env.APP_DEBUG }} > .env
          echo DB_CONNECTION=${{ env.DB_CONNECTION }} >> .env
          echo DB_HOST=${{ env.DB_HOST }} >> .env
          echo DB_DATABASE=${{ env.DB_DATABASE }} >> .env
          echo DB_USERNAME=${{ env.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ env.DB_PASSWORD }} >> .env
      # Install composer packages
      - name: Composer install
        run: composer install
      # Create database
      - name: Setup mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql --user="${{ env.DB_USERNAME }}" --password="${{ env.DB_PASSWORD }}" --execute="CREATE DATABASE ${{ env.DB_DATABASE }};"
      # Run Tests
      - name: PHP Unit Tests
        run: ./vendor/bin/phpunit
