name: Azure Start webapp

on: workflow_dispatch

jobs:
  start-webapp:
    runs-on: ubuntu-latest

    steps:
      # Login to azure
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Start azre webapp
      - name: Start WebApp
        run: |
          az webapp start --name lampsite --resource-group lampsite-rg
