name: Azure Stop webapp

on: workflow_dispatch

jobs:
  stop-webapp:
    runs-on: ubuntu-latest

    steps:
      # Login to azure
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Stop azre webapp
      - name: Stop WebApp
        run: |
          az webapp stop --name lampsite --resource-group lampsite-rg